### ISSUE TITLE
fr.yml

### ISSUE THREAD

**Issue by gilnett** [ramensoftware/windhawk-translate#37]
I don’t know if it’s an oversight, but that is missing in French.
![image](https://github.com/user-attachments/assets/70389fc4-ed73-4a93-b10e-d27b4a88d21f)

**Comment by m417z** [comment]
It was just missing a translation. It was recently translated (https://github.com/ramensoftware/windhawk-translate/pull/36), and the missing translation will be available in the next Windhawk version.
